server:
  port: 8080
  max-connections: 20
  max-threads: 100
  servlet: 
    context-path: /redisdemo
spring: 
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test2?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
    ####
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdel: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    
  redis:
#    sentinel:
#    host: r-2zef5950105f12a4.redis.rds.aliyuncs.com
    password: 1234
    host: 127.0.0.1
    port: 6379
    sentinel: 
      host: 127.0.0.1
      port: 26379
    sentinel2: 
      host: 127.0.0.1
      port: 26380
    sentinel3: 
      host: 127.0.0.1
      port: 26381
  jedis:
    pool:
      max-wait: 10000
      min-idle: 5
      max-idle: 20
      max-active: 0
      
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.demo.redisdemo.mapper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging: 
  config: classpath:logback/logback.xml

spring.devtools.restart.enabled: true
